### ISSUE TITLE
changeAction is behind when changing 'select' fields

### ISSUE THREAD

**Issue by maprules1000** [toddjordan/ember-cli-dynamic-forms#39]
changeAction is currently only called on 'click' and 'keyup' which does not fit the select field. When the 'select' field is clicked the action is called and the drop down is activated, but when the new option is selected the action is not called.

Could the 'change' action be used to trigger the changeAction function, or is there a reason only 'click' and 'keyup' are supported? (This is all in dynamic-form.js under _buildPostRender()).

I can submit a quick pr for this change too.

**Comment by toddjordan** [comment]
Hi @maprules1000 sounds reasonable.  Would love a PR ❤️
