### ISSUE TITLE
Installation Breaks (Alpaca Dependency Issue)

### ISSUE THREAD

**Issue by cameronblandford** [toddjordan/ember-cli-dynamic-forms#47]
A dependency of Alpaca ([https://github.com/flaviosilveira/Jquery-Price-Format](https://github.com/flaviosilveira/Jquery-Price-Format)) had its version information changed, breaking the most recent release of Alpaca. However, this issue has been addressed in Alpaca's head ([https://github.com/gitana/alpaca/issues/412](https://github.com/gitana/alpaca/issues/412)). Could we get an updated Alpaca dependency in bower.json?

**Comment by toddjordan** [comment]
Have you checkout out today's release (0.2.1)?  I put in some bower workarounds until alpaca comes out with a new release.

**Comment by cameronblandford** [comment]
There's a good chance I'm missing something obvious, but 
```
bower cache clean
npm install ember-cli-dynamic-forms@0.2.1 --save-dev
ember g ember-cli-dynamic-forms
```
still gives the same error. Bower still tries to install `https://github.com/flaviosilveira/Jquery-Price-Format.git#2.0.0`, and returns `No tag found that was able to satisfy 2.0.0`. Any ideas?

**Comment by toddjordan** [comment]
so the build installs clean and that's working, have you tried going a little further, like a nombom: 
`npm cache clear && bower cache clean && rm -rf node_modules bower_components && npm install && bower install`

**Comment by toddjordan** [comment]
I'll try a clean install outside the source and see if I can get it to happen

**Comment by toddjordan** [comment]
Looks like its having some problems still.  I'll try pointing it at alpaca's master branch and see if it works

**Comment by toddjordan** [comment]
@cameronblandford try out version 0.2.3 and see if that gets you there...

**Comment by cameronblandford** [comment]
You fixed it! Thanks for the help!
